"""Differentiable Longstaff-Schwartz (LSMC) early-exercise pricing.

Bermudan/American pricing on the same substrate as everything else: paths
from the QE Heston kernel, backward induction with polynomial regression via
``lax.scan``, everything jit/vmap/grad-compatible. Because the paths are
generated by the differentiable kernel, gradients flow from the LSMC price
back to the Heston parameters — early-exercise greeks by autodiff.

Conventions and caveats:

* Regression basis: ``[1, S, S^2, S^3, v, S*v]`` on normalized spot — the
  variance regressors matter under Heston (continuation value depends on v).
* The classic Longstaff-Schwartz in-the-money restriction is implemented as
  a weighted regression (ITM mask as weights), which keeps shapes static.
* The exercise decision is a hard ``where``: gradients are exact almost
  everywhere (the kink is measure-zero); do not expect useful second
  derivatives at the boundary.
"""

from __future__ import annotations

from functools import partial

import jax
import jax.numpy as jnp

from mjollnir.processes._jax_qe import qe_heston_step

__all__ = ["lsmc_price", "simulate_heston_paths"]


@partial(jax.jit, static_argnames=("n_paths", "n_steps"))
def simulate_heston_paths(key, S0, v0, dt, mu, kappa, theta, sigma_v, rho,
                          n_paths: int, n_steps: int):
    """(spot, variance) paths of shape ``(n_steps+1, n_paths)`` via QE.

    Paths are independent: one PRNG key per path (vmapped), each threaded
    through its own step chain.
    """
    keys = jax.random.split(key, n_paths)

    def one_path(k):
        def body(carry, _):
            s, v, k = carry
            s, v, k = qe_heston_step(s, v, dt, mu, kappa, theta, sigma_v, rho, key=k)
            return (s, v, k), (s, v)

        (_, _, _), (ss, vs) = jax.lax.scan(
            body, (jnp.asarray(S0), jnp.asarray(v0), k), None, length=n_steps)
        return jnp.concatenate([jnp.asarray(S0)[None], ss]), \
               jnp.concatenate([jnp.asarray(v0)[None], vs])

    spots, variances = jax.vmap(one_path)(keys)      # (n_paths, n_steps+1)
    return spots.T, variances.T


def _basis(s_norm, v):
    return jnp.stack([jnp.ones_like(s_norm), s_norm, s_norm**2, s_norm**3,
                      v, s_norm * v], axis=-1)


def _weighted_lstsq(X, y, w):
    """Solve ``argmin || sqrt(w) (X b - y) ||`` with ridge for stability."""
    Xw = X * w[:, None]
    A = Xw.T @ X + 1e-8 * jnp.eye(X.shape[1])
    return jnp.linalg.solve(A, Xw.T @ y)


def lsmc_price(spots, variances, payoff_fn, dt, r):
    """Bermudan price by Longstaff-Schwartz over precomputed paths.

    Args:
        spots, variances: ``(n_steps+1, n_paths)`` arrays (exercise allowed at
            every step after 0).
        payoff_fn: vectorized immediate-exercise payoff, e.g.
            ``lambda s: jnp.maximum(K - s, 0.0)``.
        dt: step size in years; ``r``: discount rate.

    Returns:
        Scalar price estimate (pathwise mean of optimally exercised value).
    """
    disc = jnp.exp(-r * dt)
    s_ref = spots[0, 0]
    n_steps = spots.shape[0] - 1

    value = payoff_fn(spots[-1])                     # value at maturity

    def backward(value, idx):
        t = n_steps - 1 - idx                        # n_steps-1 ... 1
        s_t, v_t = spots[t], variances[t]
        exercise = payoff_fn(s_t)
        cont_realized = value * disc
        X = _basis(s_t / s_ref, v_t)
        itm = (exercise > 0.0).astype(spots.dtype)
        beta = _weighted_lstsq(X, cont_realized, itm)
        cont_fitted = X @ beta
        take = (exercise > cont_fitted) & (exercise > 0.0)
        value = jnp.where(take, exercise, cont_realized)
        return value, None

    value, _ = jax.lax.scan(backward, value, jnp.arange(n_steps - 1))
    return jnp.mean(value * disc)                    # discount step 1 -> 0
